#!/usr/bin/env sh

string=$(cat <<EOF
    set UnixPath to POSIX path of ((path to me as text) & "::")
	tell application "Terminal"
		activate
		tell window 1
			do script "bash " & UnixPath & "../../setToken.sh"
		end tell
	end tell
EOF)

echo $string

osascript -e "$string" > /dev/null
